name: Deploy Page Object Artifacts

 -uses:-ssettings-xml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
        
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
      
  package:
  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
      
    - name: Package with Maven
      run: mvn clean package
      
    needs: build
      
  deploy:
  
   runs-on: windows-latest

   steps:
   - uses: actions/checkout@v1
   - name: Set up JDK 1.8
     uses: actions/setup-java@v1
     with:
       java-version: '1.8'
       distribution: 'temurin'
       cache: maven
      
   - name: Deploy with Maven
     run: mvn clean deploy
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   needs: [build, package]
